---
language: python
services: docker

env:
  global:
    - ROLE_NAME: ansible-rclone
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: fedora30
    - MOLECULE_DISTRO: fedora29
    - MOLECULE_DISTRO: fedora27
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1404
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian8

install:
  # Install test dependencies.
  - pip install molecule docker

script:
  # Run tests.
  - molecule test -s travis

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
