#########################################################################
# Title:         Nvidia: Nvidia Patch Task                              #
# Author(s):     desimaniac, l3uddz                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Download Nvidia patch
  get_url:
    url:  "https://raw.githubusercontent.com/keylase/nvidia-patch/master/patch.sh"
    dest: /tmp/NVIDIA-patch.sh
    mode: 0775
    owner: root
    group: root
    force: yes
    validate_certs: no

- name: Install Nvidia patch
  shell: /tmp/NVIDIA-patch.sh
  args:
    executable: /bin/bash
    warn: no
  register: patch_install
  ignore_errors: yes

- name: Nvidia patch installed!
  debug:
    msg: "Nvidia patch installed!"
  when: (patch_install is succeeded) and ('Patched!' in patch_install.stdout)

- name: Nvidia patch did not install!
  fail:
    msg:
    - "Nvidia patch did not install!"
    - "{{ patch_install.stdout }}"
  when: (patch_install is failed) or ('Patched!' not in patch_install.stdout)