#!/bin/bash
#
# Title:      Traktarr auto deploy
# Mod from MrDoobPG for PTS
# GNU:        General Public License v3.0
# Origin:     https://github.com/l3uddz/plex_patrol
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

   - name: Add Traktarr prefilling list @ daily
     cron:
       name: "Traktarr prefilling list @ daily"
       special_time: 'daily'
       job: 'bash /opt/plexguide/menu/traktarr/traktarr-list/traktarr.sh >/dev/null 2>&1'
       state: absent

   - name: Add Traktarr prefilling list @ daily
     cron:
       name: "Traktarr prefilling list @ daily"
       special_time: 'daily'
       job: 'bash /opt/plexguide/menu/traktarr/traktarr-list/traktarr.sh 1>/dev/null 2>&1'
       state: present