#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'oauth'
        intport: '4181'
        extport: '4181'
        image: 'thomseddon/traefik-forward-auth'

    # CORE (MANDATORY) ############################################################
    - name: CronJob Role
      include_tasks: '/opt/coreapps/apps/_core.yml'

    - name: Register Auth Path
      shell: 'cat /var/plexguide/shield.clientid'
      register: clientid

    - name: Register Client Secret
      shell: 'cat /var/plexguide/shield.clientsecret'
      register: clientsecret

    - name: Register Secret
      shell: 'openssl rand -hex 16'
      register: secret

    - name: Register WhiteListed E-Mails
      shell: 'cat /var/plexguide/pgshield.compiled'
      register: whitelisted

    # LABELS ######################################################################

    - name: 'Setting PG Labels'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '4181'
          traefik.backend: 'oauth'
          traefik.frontend.rule: 'Host:oauth.{{domain.stdout}}'
          traefik.frontend.auth.forward.address: 'http://oauth:4181'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'
          CLIENT_ID: '{{clientid.stdout}}'
          CLIENT_SECRET: '{{clientsecret.stdout}}'
          SECRET: '{{secret.stdout}}'
          COOKIE_DOMAIN: '{{domain.stdout}}'
          COOKIE_SECURE: 'True'
          LIFETIME: '2592000'
          AUTH_HOST: 'oauth.{{domain.stdout}}'
          WHITELIST: '{{whitelisted.stdout}}'
    # MAIN DEPLOYMENT #############################################################

    - name: 'Deploying Container - {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: 'yes'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - 'plexguide'
        state: started
        labels: '{{pg_labels}}'
