#########################################################################
# Title:         System: CPU Frequency Tasks                            #
# Author(s):     l3uddz, EnorMOZ, desimaniac                            #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Install 'cpufrequtils'
  apt:
    name: cpufrequtils
    state: present

- name: Install 'linux-tools' for Ubuntu
  apt:
    state: present
    name:
      - linux-tools-common
      - linux-tools-generic
  when: ansible_distribution == 'Ubuntu'

- name: Install 'linux-tools' for Debian
  apt:
    name: linux-tools
    state: present
  when: ansible_distribution == 'Debian'

- name: "Install linux-tools-{{ ansible_kernel }}"
  shell: "apt-get install -qq $(apt-cache search -n linux-tools-{{ ansible_kernel }} | awk '{print $1}' | tail -n 1)"
  ignore_errors: yes

- name: Check /etc/default/cpufrequtils exists
  stat:
    path: /etc/default/cpufrequtils
  register: cpufrequtils_file

- name: Create /etc/default/cpufrequtils
  file:
    path: /etc/default/cpufrequtils
    state: touch
  when: not cpufrequtils_file.stat.exists

- name: Set CPU frequency scaling governor to performance
  lineinfile:
    path: "/etc/default/cpufrequtils"
    regexp: '^GOVENOR\s?='
    line: 'GOVENOR="performance"'
    state: present

- name: Set CPU frequency scaling governor to performance
  lineinfile:
    path: "/etc/default/cpufrequtils"
    regexp: '^GOVERNOR\s?='
    line: 'GOVERNOR="performance"'
    state: present

- name: Ensure governor is enabled
  lineinfile:
    path: "/etc/default/cpufrequtils"
    regexp: '^ENABLE\s?='
    line: 'ENABLE="true"'
    state: present

- name: Disable ondemand CPU frequency scaling daemon
  shell: "update-rc.d ondemand disable"
  when: ansible_distribution_version == "16.04"
