#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: True
  tasks:
    - name: Install Common Packages (Takes Awhile)
      apt: 'name={{item.package}} state=present'
      with_items:
        - { package: 'fuse' }
        - { package: 'nano' }
        - { package: 'fail2ban' }
        - { package: 'wget' }
        - { package: 'lsb-release' }
        - { package: 'figlet' }
        - { package: 'software-properties-common' }
        - { package: 'unzip' }
        - { package: 'glances' }
        - { package: 'python-pip' }
        - { package: 'python3-pip' }
        - { package: 'python-passlib' }
        - { package: 'zip' }
        - { package: 'curl' }
        - { package: 'man-db' }
        - { package: 'htop' }
        - { package: 'openssh-server' }
        - { package: 'dirmngr' }
        - { package: 'zip' }
        - { package: 'apt-transport-https' }
        - { package: 'ca-certificates' }
        - { package: 'tree' }
        - { package: 'ncdu' }
        - { package: 'ctop' }
        - { package: 'dialog' }
        - { package: 'dnsutils' }
        - { package: 'mc' }
        - { package: 'apache2-utils' }
        - { package: 'lsof' }
        - { package: 'pwgen' }
        - { package: 'gawk' }
        - { package: 'python-lxml' }
        - { package: 'acl' }
        - { package: 'bc' }
        - { package: 'gnupg2' }
        - { package: 'python-apt' }
        - { package: 'rsync' }
        - { package: 'python-docker' }
        - { package: 'unrar' }        

    - name: Update pip packages for python3
      pip:
        name:
          - pip
          - setuptools
          - pyOpenSSL
          - requests
          - netaddr
          - lxml
        state: latest
        executable: pip3
