---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Register Role
      shell: 'cat /var/plexguide/pgcloner.projectname'
      register: pname

    - name: Register Role
      shell: 'cat /var/plexguide/pgcloner.rolename'
      register: prole

    - name: Register User - Personal
      shell: 'cat /var/plexguide/{{prole.stdout}}.user'
      register: user

    - name: Register Branch - Personal
      shell: 'cat /var/plexguide/{{prole.stdout}}.branch'
      register: branch

    - name: 'Cloning Personal Forked Role'
      git:
        repo: 'https://github.com/{{user.stdout}}/{{pname.stdout}}'
        dest: '/opt/{{prole.stdout}}'
        version: '{{branch.stdout}}'
        force: yes

    - name: 'Setting permissions on scripts'
      shell: 'chmod -R 775 /opt/{{prole.stdout}}'

    - name: 'Setting permissions on scripts'
      shell: 'chown -cR 1000:1000 /opt/{{prole.stdout}}'
