server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://loki:3100/loki/api/v1/push

scrape_configs:
 - job_name: pgvar
   pipeline_stages:
   - docker:
   static_configs:
   - targets:
      - localhost
     labels:
      job: pgvar
      host: yourhost
      __path__: /var/log/*.log

 - job_name: uploader
   pipeline_stages:
   - docker:
   static_configs:
   - targets:
      - localhost
     labels:
      job: uploader
      host: yourhost
      __path__: /var/log/uploader/*.log

 - job_name: mounts
   pipeline_stages:
   - docker:
   static_configs:
   - targets:
      - localhost
     labels:
      job: mounts
      host: yourhost
      __path__: /var/log/drive/*.log

 - job_name: emergency
   pipeline_stages:
   - docker:
   static_configs:
   - targets:
      - localhost
     labels:
      job: emergency
      host: yourhost
      __path__: /var/log/emergency/*.log
