#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
# Credit to ENZTV for the basis of this script https://enztv.wordpress.com/2017/03/09/unionfs-cleanup/
###############################################
---
- name: Install gdriveclean; remove old cronjob
  cron:
    name: 'gdriveclean'
    user: 'root'
    state: absent
  ignore_errors: yes

- name: Install gdriveclean; remove existing unionfs-fuse whiteout files
  file:
    state: absent
    path: '/mnt/move/.unionfs-fuse'

- name: remove gdriveclean; cronjob
  cron:
    name: 'gdriveclean'
    state: absent
  ignore_errors: yes
