---
- name: Install Journald Fix
  template:
    dest: /etc/systemd/journald.conf
    force: true
    src: /opt/plexguide/menu/journal/templates/journald.conf.j2

- name: systemd reloading
  systemd:
    daemon_reload: true

- name: restart journald
  systemd:
    daemon_reload: true
    name: systemd-journald
    state: restarted
