#!/bin/bash
#
# Title:      rclone dedupe
# Authors:    MrDoob
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

  - name: 'remove Weekly rclone dedupe'
    cron:
      name: 'Weekly rclone dedupe running'
      special_time: 'weekly'
      job: 'bash /opt/plexguide/menu/rclonededupe/dupe.sh >/dev/null 2>&1'
      state: 'absent'
    ignore_errors: yes