#!/bin/bash
#
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'telegraf'
        intport: '8125'
        extport: '8125'
        image: 'telegraf:alpine'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/plexguide/menu/new_ui/ymls/_core.yml'

    - name: 'Checking for existing telegraf.conf'
      stat:
        path: '/opt/appdata/{{pgrole}}/telegraf.conf'
      register: stat_result

    - name: 'Clone telegraf.conf for first start'
      include_tasks: '/opt/plexguide/menu/new_ui/templates/telegraf/telegraf-conf.yml'
      when: stat_result.stat.exists == False
      ignore_errors: yes

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}{{tldset}}{{cname}}'
          traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'

    - name: 'Setting {{pgrole}} Volumes'
      set_fact:
        pg_volumes:
          - '{{path.stdout}}:{{path.stdout}}'
          - '/etc/localtime:/etc/localtime:ro'
          - '/opt/appdata/{{pgrole}}/:/etc/telegraf/'
          - '/var/run/docker.sock:/var/run/docker.sock'
          - '/:/rootfs'
          - '/proc:/rootfs/proc'
          - '/sys:/rootfs/sys'
          - '/var/run/utmp:/var/run/utmp'
          - '/var/plexguide/logs:/logs/'

    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'
          HOST_PROC: '/rootfs/proc'
          HOST_SYS: '/rootfs/sys'
          HOST_ETC: '/rootfs/etc'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        capabilities:
          - SYS_PTRACE
        security_opts:
          - apparmor:unconfined
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'

