#!/bin/bash
#
# Title:      Plex_DupeFinder remover
# YML Author: MrDoob
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS ######################################################################
    - name: Check Plex Dupefinder Existance
      stat:
        path: '/usr/local/bin/plex_dupefinder'
      register: pgp

    - name: Remove Plex Dupefinder Basic Directories
      file: 'path={{item}} state=absent mode=0775 owner=1000 group=1000'
      with_items:
        - '/opt/plex_dupefinder'
        - '/var/plex_dupe/'
      when: pgp.stat.exists